// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWlWkKIqL5UfbxL3XAuxKiXYlDSKx_SuI',
    appId: '1:666046253868:web:c85865ba56244860a5fa89',
    messagingSenderId: '666046253868',
    projectId: 'zonestore-65e1a',
    authDomain: 'zonestore-65e1a.firebaseapp.com',
    storageBucket: 'zonestore-65e1a.appspot.com',
    measurementId: 'G-Z2BXDG9FRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBConL-CjhTTDZj89jCsrj9fTdfdJwYZis',
    appId: '1:666046253868:android:da10e108c523daf7a5fa89',
    messagingSenderId: '666046253868',
    projectId: 'zonestore-65e1a',
    storageBucket: 'zonestore-65e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1RciPegNJY54NeTIrxFWOnGdeC8Vx1Yo',
    appId: '1:666046253868:ios:98b3a42301e28f25a5fa89',
    messagingSenderId: '666046253868',
    projectId: 'zonestore-65e1a',
    storageBucket: 'zonestore-65e1a.appspot.com',
    androidClientId: '666046253868-o9a7beu3na0dabfh6uherjte7feunq7d.apps.googleusercontent.com',
    iosClientId: '666046253868-u1ruvlhokcr72buh271bur1jo8b2a4si.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoneStore',
  );
}
